export const products = [
  [
    {
      image: require('../products-images/tabaka.png'),
      name: 'Цыпленок табака',
      description: 'со сливочным соусом из лесных грибов',
      price: 430,
      count: 1,
    },
    {
      image: require('../products-images/svinya.png'),
      name: 'Свиной стейк',
      description: 'с морковным соусом и микрозеленью',
      price: 500,
      count: 1,
    },
    {
      image: require('../products-images/loses-stake.png'),
      name: 'Стейк из лосося',
      description: 'с томатами,спаржей,на картофельной подушке',
      price: 520,
      count: 1,
    },
    {
      image: require('../products-images/telyatina.png'),
      name: 'Стейк из телятины',
      description: 'сделанный на гриле, с розмарином и соусом на выбор',
      price: 485,
      count: 1,
    },
    {
      image: require('../products-images/dorado.png'),
      name: 'Дорадо',
      description: 'в кисло-сладком соусе с овощами',
      price: 680,
      count: 1,
    },
  ],
  [
    {
      image: require('../products-images/loses.png'),
      name: 'Салат с теплым лососем',
      description: 'с сулугуни, апельсином, и зеленью',
      price: 500,
      count: 1,
    },
    {
      image: require('../products-images/kamamber.png'),
      name: 'Салат с жареным камамбером ',
      description: 'клубникой,и микрозеленью',
      price: 460,
      count: 1,
    },
    {
      image: require('../products-images/greceskiy.png'),
      name: 'Греческий салат',
      description: 'с творожным сыром и бальзамическим соусом',
      price: 430,
      count: 1,
    },
    {
      image: require('../products-images/proshutto-grusha.png'),
      name: 'Салат с прошутто и грушей',
      description: 'с хрустящми гренками и базиликом',
      price: 525,
      count: 1,
    },
    {
      image: require('../products-images/telyatina.png'),
      name: 'Салат с телятиной ',
      description: 'с ягодами и кисло-сладким соусом',
      price: 580,
      count: 1,
    },
  ],
  [
    {
      image: require('../products-images/parfe.png'),
      name: 'Фисташковое парфе',
      description: 'с ягодами и мятой',
      price: 350,
      count: 1,
    },
    {
      image: require('../products-images/vafli.png'),
      name: 'Бельгийские вафли',
      description: 'со сливочным мороженым',
      price: 300,
      count: 1,
    },
    {
      image: require('../products-images/barxat.png'),
      name: 'Красный бархат',
      description: 'с вишневой начинкой и шоколадом',
      price: 425,
      count: 1,
    },
    {
      image: require('../products-images/medovik.png'),
      name: 'Медовик ягодный',
      description: 'в сливочном креме, с сезонными ягодами',
      price: 430,
      count: 1,
    },
    {
      image: require('../products-images/milfey.png'),
      name: 'Мильфей',
      description: 'карамельно-сливочный, со свежими ягодами',
      price: 280,
      count: 1,
    },
  ],
];
